# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8409fd1176f55508cac2982c574400c629b6c577b072e9420a334c2bc425f698c1851a1e4f7717a64cc7d3bc8a7cecca67c9b69770f5406eac379b610dc0712

test:
  secret_key_base: 8c5a865cc00b2f7f34a3e6f5c05214558e7f514476ad7b1b3c590dc6c5ecef2f79de670aef8acdf75b3110eef54f41c4e7d7ffe5c4da905fe2435afe73f7b1da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
